@startuml
class DashboardView <<partial>> {
    +  <<event>> ChangePasswordClicked : EventHandler? 
    + DashboardView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + Welcome : string <<get>> <<set>>
    + ShowChangePassword : bool <<get>> <<set>>
    + CleanUp() : void
}
Form <|-- DashboardView
IThemeable <|-- DashboardView
IDashboardView <|-- DashboardView
DashboardView --> "LastPasswordChange" DateTime
@enduml
