@startuml
class MasterView <<partial>> {
    +  <<event>> PreviewToggleChanged : EventHandler<ToggleEventArgs>? 
    +  <<event>> ToggleChanged : EventHandler<string>? 
    +  <<event>> SignOut : EventHandler? 
    + MasterView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + GenerateMenu(menuItems:string[][]) : void
    + UsernameText : string <<set>>
    + SetSideMenuToggledIndex(i:int, j:int, toggled:bool) : void
    + DisplayChildView(childView:IChildView) : void
    + ShowMessageBox(text:string, caption:string, buttons:MessageBoxButtons) : DialogResult
    + CleanUp() : void
}
Form <|-- MasterView
IMasterView <|-- MasterView
IThemeable <|-- MasterView
MasterView --> "ChildView" IChildView
@enduml
