@startuml
class ReportView <<partial>> {
    +  <<event>> Download : EventHandler? 
    +  <<event>> Back : EventHandler? 
    + ReportView()
    + Theme() : void
    + SetFont() : void
    + SetToolTipVisibility() : void
    + ReportName : string <<get>> <<set>>
    + BackVisible : bool <<set>>
    + ShowMessageBox(text:string, caption:string, buttons:MessageBoxButtons) : DialogResult
    + CleanUp() : void
    + GetFileName(name:string) : bool
}
Form <|-- ReportView
IThemeable <|-- ReportView
IReportView <|-- ReportView
@enduml
