@startuml
class DashboardPresenter {
    +  <<event>> NavigationRequest : EventHandler<NavigationEventArgs>? 
    + DashboardPresenter(view:IDashboardView, staff:StaffModel)
    + CanExit() : bool
}
class "BasePresenter`1"<T> {
}
"BasePresenter`1" "<IDashboardView>" <|-- DashboardPresenter
INavigatingPresenter <|-- DashboardPresenter
IChildPresenter <|-- DashboardPresenter
@enduml
