@startuml
class SignInPresenter {
    +  <<event>> SignInSuccessful : EventHandler<StaffModel>? 
    +  <<event>> FormClosed : EventHandler? 
    + SignInPresenter(view:ISignInView)
    + Show() : void
    + Close() : void
    + <<override>> CleanUp() : void
}
class "BasePresenter`1"<T> {
}
"BasePresenter`1" "<ISignInView>" <|-- SignInPresenter
@enduml
