@startuml
class CleaningJobFactory {
    + {static} CreateBookCleaningJob() : (BookCleaningJobView view, BookCleaningJobPresenter presenter)
    + {static} CreateManageCleaningJobDetails() : (ManageCleaningJobDetailsView view, ManageCleaningJobDetailsPresenter presenter)
    + {static} CreateSelectCleaningJobOptions(getCleaningJobOptions:Task<List<CleaningJobOptionModel>>) : (SelectCleaningJobOptionsView view, SelectCleaningJobOptionsPresenter presenter)
    + {static} CreateManageCleaningJobOptions() : (ManageCleaningJobOptionsView view, ManageCleaningJobOptionsPresenter presenter)
    + {static} CreateManageCleaningJobDuration() : (ManageCleaningJobDurationView view, ManageCleaningJobDurationPresenter presenter)
    + {static} CreateSelectCleaningJobCustomer() : (SelectCleaningJobCustomerView view, SelectCleaningJobCustomerPresenter presenter)
    + {static} CreateSelectCleaningJobStaff(getStaff:Task<List<StaffModel>>) : (SelectCleaningJobStaffView view, SelectCleaningJobStaffPresenter presenter)
    + {static} CreateEditCleaningJob(model:CleaningJobModel) : (EditCleaningJobView view, EditCleaningJobPresenter presenter)
}
@enduml
