@startuml
class StaffFactory <<static>> {
    + {static} CreatePersonalInformationSettings(staff:StaffModel) : (PersonalInformationSettingsView view, PersonalInformationSettingsPresenter presenter)
    + {static} CreateContactDetailsSettingsView(staff:StaffModel) : (ContactDetailsSettingsView view, ContactDetailsSettingsPresenter presenter)
    + {static} CreateEmergencyContactSettings(staff:StaffModel) : (EmergencyContactSettingsView view, EmergencyContactSettingsPresenter presenter)
    + {static} CreateAppearanceSettings(staff:StaffModel) : (AppearanceSettingsView view, AppearanceSettingsPresenter presenter)
    + {static} CreateSecuritySettings(staff:StaffModel) : (SecuritySettingsView view, SecuritySettingsPresenter presenter)
    + {static} CreateStockDisplay(staff:StaffModel) : (DisplayStockView view, DisplayStockPresenter presenter)
    + {static} CreateManageStockQuantity() : (ManageStockQuantityView view, ManageStockQuantityPresenter presenter)
    + {static} CreateManageStockDetails() : (ManageStockDetailsView view, ManageStockDetailsPresenter presenter)
    + {static} CreateManageStockWarning() : (ManageStockWarningView view, ManageStockWarningPresenter presenter)
    + {static} CreateChangeStaffPassword(staff:StaffModel) : (ChangeStaffPasswordView view, ChangeStaffPasswordPresenter presenter)
    + {static} CreateAddStock(staff:StaffModel) : (AddStockView view, AddStockPresenter presenter)
    + {static} CreateEditStock(stockItem:StockModel, staff:StaffModel) : (EditStockView view, EditStockPresenter presenter)
    + {static} CreateDisplayStockQuantityChanges() : (DisplayStockQuantityChangesView view, DisplayStockQuantityChangesPresenter presenter)
    + {static} CreateViewStockQuantityChange(stockQuantityChange:StockQuantityChange) : (ViewStockQuantityChangeView view, ViewStockQuantityChangePresenter presenter)
    + {static} CreateDisplayStaff(staff:StaffModel) : (DisplayStaffView view, DisplayStaffPresenter presenter)
    + {static} CreateManageStaffAppearanceSettings() : (ManageStaffAppearanceSettingsView view, ManageStaffAppearanceSettingsPresenter presenter)
    + {static} CreateEditStaff(model:StaffModel, staff:StaffModel) : (EditStaffView view, EditStaffPresenter presenter)
    + {static} CreateManageStaffPersonalInformation() : (ManageStaffPersonalDetailsView view, ManageStaffPersonalDetailsPresenter presenter)
    + {static} CreateManageStaffContactDetails() : (ManageStaffContactDetailsView view, ManageStaffContactDetailsPresenter presenter)
    + {static} CreateManageStaffEmergencyContactDetails() : (ManageStaffEmergencyContactDetailsView view, ManageStaffEmergencyContactDetailsPresenter presenter)
    + {static} CreateManageStaffCredentials() : (ManageStaffCredentialsView view, ManageStaffCredentialsPresenter presenter)
    + {static} CreateManageStaffPassword() : (ManageStaffPasswordView view, ManageStaffPasswordPresenter presenter)
    + {static} CreateAddStaff(staff:StaffModel) : (AddStaffView view, AddStaffPresenter presenter)
}
@enduml
