@startuml
class AddEditDeleteSearchBar <<partial>> {
    +  <<event>> SearchTextChanged : EventHandler? 
    +  <<event>> Search : EventHandler? 
    +  <<event>> Edit : EventHandler? 
    +  <<event>> View : EventHandler? 
    +  <<event>> Add : EventHandler? 
    +  <<event>> Delete : EventHandler? 
    + AddEditDeleteSearchBar()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SearchText : string <<get>> <<set>>
    + AddEnabled : bool <<get>> <<set>>
    + EditEnabled : bool <<get>> <<set>>
    + DeleteEnabled : bool <<get>> <<set>>
    + SearchEnabled : bool <<get>> <<set>>
    + ViewMode : bool <<get>> <<set>>
    + SetFont() : void
}
UserControl <|-- AddEditDeleteSearchBar
IThemeable <|-- AddEditDeleteSearchBar
@enduml
