@startuml
class PreviousNextDoneBar <<partial>> {
    +  <<event>> Previous : EventHandler? 
    +  <<event>> Next : EventHandler? 
    +  <<event>> Done : EventHandler? 
    + PreviousNextDoneBar()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + PreviousVisible : bool <<get>> <<set>>
    + NextVisible : bool <<get>> <<set>>
    + DoneVisible : bool <<get>> <<set>>
}
UserControl <|-- PreviousNextDoneBar
IThemeable <|-- PreviousNextDoneBar
@enduml
