@startuml
class SearchBar <<partial>> {
    +  <<event>> SearchTextChanged : EventHandler? 
    +  <<event>> Search : EventHandler? 
    + SearchBar()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SearchText : string <<get>> <<set>>
    + SetFont() : void
}
UserControl <|-- SearchBar
IThemeable <|-- SearchBar
@enduml
