@startuml
class AddStaffView <<partial>> {
    +  <<event>> Next : EventHandler? 
    +  <<event>> Previous : EventHandler? 
    +  <<event>> Done : EventHandler? 
    +  <<event>> Back : EventHandler? 
    + AddStaffView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + DisplayChildView(childView:IChildView) : void
    + ShowMessageBox(text:string, caption:string, buttons:MessageBoxButtons) : DialogResult
    + IsLoading : bool <<get>> <<set>>
    + NextVisible : bool <<get>> <<set>>
    + PreviousVisible : bool <<get>> <<set>>
    + DoneVisible : bool <<get>> <<set>>
    + CleanUp() : void
}
Form <|-- AddStaffView
IAddStaffView <|-- AddStaffView
IThemeable <|-- AddStaffView
IChildView <|-- AddStaffView
@enduml
