@startuml
class ChangeStaffPasswordView <<partial>> {
    +  <<event>> UsernameChanged : EventHandler? 
    +  <<event>> NewPasswordChanged : EventHandler? 
    +  <<event>> ChangePassword : EventHandler? 
    + ChangeStaffPasswordView()
    + SetPresenter(presenter:ChangeStaffPasswordPresenter) : void
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + IsLoading : bool <<get>> <<set>>
    + Username : string <<get>>
    + NewPassword : string <<get>>
    + ConfirmPassword : string <<get>>
    + Reset() : void
    + EightLong : bool <<get>> <<set>>
    + Number : bool <<get>> <<set>>
    + SpecialCharacter : bool <<get>> <<set>>
    + UppercaseLowercase : bool <<get>> <<set>>
    + PasswordError : string <<set>>
    + UsernameError : string <<set>>
    + SetUsernameBorderError(isError:bool) : void
    + SetNewPasswordBorderError(isError:bool) : void
    + SetConfirmPasswordBorderError(isError:bool) : void
    + DockInParent : bool <<get>>
    + ShowMessageBox(text:string, caption:string, buttons:MessageBoxButtons) : DialogResult
    + CanExit() : bool
    + CleanUp() : void
}
Form <|-- ChangeStaffPasswordView
IChangePasswordView <|-- ChangeStaffPasswordView
@enduml
