@startuml
class ManageStaffPersonalDetailsView <<partial>> {
    +  <<event>> ForenameChanged : EventHandler? 
    +  <<event>> SurnameChanged : EventHandler? 
    +  <<event>> DateOfBirthChanged : EventHandler? 
    + ManageStaffPersonalDetailsView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + Forename : string <<get>> <<set>>
    + Surname : string <<get>> <<set>>
    + NameError : string <<get>> <<set>>
    + DateOfBirthError : string <<get>> <<set>>
    + DateOfBirthValid : bool <<get>>
    + SetForenameBorderError(isError:bool) : void
    + SetSurnameBorderError(isError:bool) : void
    + CleanUp() : void
}
Form <|-- ManageStaffPersonalDetailsView
IManageStaffPersonalInformationView <|-- ManageStaffPersonalDetailsView
IThemeable <|-- ManageStaffPersonalDetailsView
ManageStaffPersonalDetailsView --> "DateOfBirth" DateTime
@enduml
