@startuml
class ManageStaffAppearanceSettingsView <<partial>> {
    +  <<event>> FontNameChanged : EventHandler? 
    +  <<event>> DarkModeCheckedChanged : EventHandler? 
    +  <<event>> ToolTipsCheckedChanged : EventHandler? 
    + ManageStaffAppearanceSettingsView()
    + Theme() : void
    + SetFont() : void
    + SetToolTipVisibility() : void
    + DarkModeChecked : bool <<get>> <<set>>
    + ShowToolTipsChecked : bool <<get>> <<set>>
    + FontName : string <<get>> <<set>>
    + CleanUp() : void
}
Form <|-- ManageStaffAppearanceSettingsView
IThemeable <|-- ManageStaffAppearanceSettingsView
IManageStaffAppearanceSettingsView <|-- ManageStaffAppearanceSettingsView
@enduml
