@startuml
class ManageStaffPasswordView <<partial>> {
    +  <<event>> PasswordChanged : EventHandler? 
    +  <<event>> ConfirmPasswordChanged : EventHandler? 
    + ManageStaffPasswordView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + Password : string <<get>> <<set>>
    + ConfirmPassword : string <<get>> <<set>>
    + EightLong : bool <<get>> <<set>>
    + Number : bool <<get>> <<set>>
    + SpecialCharacter : bool <<get>> <<set>>
    + UppercaseLowercase : bool <<get>> <<set>>
    + PasswordError : string <<set>>
    + SetPasswordBorderError(isError:bool) : void
    + SetConfirmPasswordBorderError(isError:bool) : void
    + CleanUp() : void
}
Form <|-- ManageStaffPasswordView
IManageStaffPasswordView <|-- ManageStaffPasswordView
IChildView <|-- ManageStaffPasswordView
IThemeable <|-- ManageStaffPasswordView
@enduml
