@startuml
class ManageStaffCredentialsView <<partial>> {
    +  <<event>> UsernameChanged : EventHandler? 
    +  <<event>> PrivilegeLevelChanged : EventHandler? 
    + ManageStaffCredentialsView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + Username : string <<get>> <<set>>
    + SuggestedUsername : string <<set>>
    + SelectedPrivilegeLevel : string <<get>> <<set>>
    + UsernameError : string <<set>>
    + SetUsernameBorderError(isError:bool) : void
    + CleanUp() : void
}
Form <|-- ManageStaffCredentialsView
IThemeable <|-- ManageStaffCredentialsView
IManageStaffCredentialsView <|-- ManageStaffCredentialsView
@enduml
