@startuml
class ManageStockDetailsView <<partial>> {
    +  <<event>> DescriptionChanged : EventHandler? 
    +  <<event>> NameChanged : EventHandler? 
    +  <<event>> SkuChanged : EventHandler? 
    +  <<event>> ArchivedChanged : EventHandler? 
    + ManageStockDetailsView()
    + Theme() : void
    + SetFont() : void
    + SetToolTipVisibility() : void
    + StockName : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Sku : string <<get>> <<set>>
    + Archived : bool <<get>> <<set>>
    + IsLoading : bool <<get>> <<set>>
    + NameSkuError : string <<set>>
    + SetCharacterCount(number:int) : void
    + SetNameBorderError(isError:bool) : void
    + SetSKUBorderError(isError:bool) : void
    + CleanUp() : void
}
Form <|-- ManageStockDetailsView
IManageStockDetailsView <|-- ManageStockDetailsView
IThemeable <|-- ManageStockDetailsView
@enduml
