@startuml
class ManageStockPriceView <<partial>> {
    +  <<event>> PriceChanged : EventHandler? 
    + ManageStockPriceView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + LowQuantity : int <<get>> <<set>>
    + HighQuantity : int <<get>> <<set>>
    + CleanUp() : void
}
Form <|-- ManageStockPriceView
IThemeable <|-- ManageStockPriceView
@enduml
