@startuml
interface IChangePasswordView {
    +  <<event>> NewPasswordChanged : EventHandler? 
    +  <<event>> UsernameChanged : EventHandler? 
    +  <<event>> ChangePassword : EventHandler? 
    + Username : string <<get>>
    + NewPassword : string <<get>>
    + ConfirmPassword : string <<get>>
    + Reset() : void
    + SetUsernameBorderError(isError:bool) : void
    + SetNewPasswordBorderError(isError:bool) : void
    + SetConfirmPasswordBorderError(isError:bool) : void
    + EightLong : bool <<get>> <<set>>
    + Number : bool <<get>> <<set>>
    + SpecialCharacter : bool <<get>> <<set>>
    + UppercaseLowercase : bool <<get>> <<set>>
    + IsLoading : bool <<get>> <<set>>
    + PasswordError : string <<set>>
    + UsernameError : string <<set>>
    + ShowMessageBox(text:string, caption:string, buttons:MessageBoxButtons) : DialogResult
}
IThemeable <|-- IChangePasswordView
IChildView <|-- IChangePasswordView
@enduml
