@startuml
interface IManageStaffCredentialsView {
    +  <<event>> UsernameChanged : EventHandler? 
    +  <<event>> PrivilegeLevelChanged : EventHandler? 
    + SuggestedUsername : string <<set>>
    + Username : string <<get>> <<set>>
    + SelectedPrivilegeLevel : string <<get>> <<set>>
    + UsernameError : string <<set>>
    + SetUsernameBorderError(isError:bool) : void
}
IChildView <|-- IManageStaffCredentialsView
@enduml
