@startuml
interface IManageStaffAppearanceSettingsView {
    +  <<event>> DarkModeCheckedChanged : EventHandler? 
    +  <<event>> ToolTipsCheckedChanged : EventHandler? 
    +  <<event>> FontNameChanged : EventHandler? 
    + DarkModeChecked : bool <<get>> <<set>>
    + ShowToolTipsChecked : bool <<get>> <<set>>
    + FontName : string <<get>> <<set>>
}
IChildView <|-- IManageStaffAppearanceSettingsView
@enduml
