@startuml
interface IManageStaffPasswordView {
    +  <<event>> PasswordChanged : EventHandler? 
    +  <<event>> ConfirmPasswordChanged : EventHandler? 
    + Password : string <<get>> <<set>>
    + ConfirmPassword : string <<get>> <<set>>
    + EightLong : bool <<get>> <<set>>
    + Number : bool <<get>> <<set>>
    + SpecialCharacter : bool <<get>> <<set>>
    + UppercaseLowercase : bool <<get>> <<set>>
    + SetPasswordBorderError(isError:bool) : void
    + SetConfirmPasswordBorderError(isError:bool) : void
    + PasswordError : string <<set>>
}
IChildView <|-- IManageStaffPasswordView
@enduml
