@startuml
class DisplayLoginAttemptModel {
    + Username : string <<get>> <<set>>
    + Successful : bool <<get>> <<set>>
    + DisplayLoginAttemptModel(loginAttempt:LoginAttemptModel)
    +  <<event>> PropertyChanged : PropertyChangedEventHandler? 
}
INotifyPropertyChanged <|-- DisplayLoginAttemptModel
DisplayLoginAttemptModel --> "AttemptTime" DateTime
@enduml
