@startuml
class DisplayLoginAttemptView <<partial>> {
    +  <<event>> Search : EventHandler? 
    +  <<event>> SortRequested : EventHandler<SortRequestEventArgs>? 
    + DisplayLoginAttemptView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + SearchText : string <<get>> <<set>>
    + DataGridText : string <<get>> <<set>>
    + DisplayItems(items:BindingList<DisplayLoginAttemptModel>) : void
    + DisableAll() : void
    + EnableAll() : void
    + ShowMessageBox(text:string, caption:string, buttons:MessageBoxButtons) : DialogResult
    + CleanUp() : void
}
Form <|-- DisplayLoginAttemptView
IThemeable <|-- DisplayLoginAttemptView
IDisplayLoginAttemptView <|-- DisplayLoginAttemptView
DisplayLoginAttemptView --> "SelectedItem" DisplayLoginAttemptModel
@enduml
