@startuml
class AppearanceSettingsPresenter {
    + AppearanceSettingsPresenter(view:IAppearanceSettings, staff:StaffModel)
    + <<override>> CleanUp() : void
}
class "SettingsPresenter`1"<T> {
}
"SettingsPresenter`1" "<IAppearanceSettings>" <|-- AppearanceSettingsPresenter
@enduml
