@startuml
abstract class "SettingsPresenter`1"<TView> {
    + SettingsPresenter(view:TView, staff:StaffModel)
    + <<virtual>> CanExit() : bool
    + <<override>> CleanUp() : void
}
class "BasePresenter`1"<T> {
}
"BasePresenter`1" "<TView>" <|-- "SettingsPresenter`1"
IChildPresenter <|-- "SettingsPresenter`1"
@enduml
