@startuml
class StaffModel {
    + Id : int <<get>> <<set>>
    + Username : string <<get>> <<set>>
    + Archived : bool <<get>> <<set>>
    + Forename : string <<get>> <<set>>
    + Surname : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + PhoneNumber : string <<get>> <<set>>
    + Address : string <<get>> <<set>>
    + EmergencyContactForename : string <<get>> <<set>>
    + EmergencyContactSurname : string <<get>> <<set>>
    + EmergencyContactPhoneNumber : string <<get>> <<set>>
}
StaffModel o-> "LastPasswordChange" DateTime
StaffModel o-> "PrivilegeLevel" PrivilegeLevel
StaffModel o-> "DateOfBirth" DateTime
StaffModel o-> "Theme" Theme
@enduml
