@startuml
class MenuButton <<partial>> {
    + MenuButton()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + <<new>>  <<event>> Click : EventHandler? 
    + <<new>> Text : string <<get>> <<set>>
}
UserControl <|-- MenuButton
IThemeable <|-- MenuButton
MenuButton --> "IconImage" Image
MenuButton --> "BackColor" Color
@enduml
