@startuml
class TopMenuItem <<partial>> {
    + <<new>>  <<event>> Click : EventHandler? 
    + TopMenuItem()
    + Theme() : void
    + <<new>> Text : string <<get>> <<set>>
    + Selected : bool <<get>> <<set>>
}
UserControl <|-- TopMenuItem
@enduml
