@startuml
class CleaningJobDAL {
    + {static} <<async>> GetCleaningJobs() : Task<List<CleaningJobModel>>
    + {static} <<async>> GetCleaningJobsByDate(date:DateTime) : Task<List<CleaningJobModel>>
    + {static} <<async>> GetCleaningJobStaffIds(id:int) : Task<List<int>>
    + {static} <<async>> DeleteCleaningJob(id:int) : Task<bool>
    + {static} <<async>> GetCleaningJobCleaningOptions(id:int) : Task<List<CleaningJobOptionModel>>
    + {static} <<async>> UpdateCleaningJobDetails(id:int, address:string, extraInformation:string) : Task<bool>
    + {static} <<async>> UpdateCleaningJobTimes(id:int, startDate:DateTime, endDate:DateTime) : Task<bool>
    + {static} <<async>> UpdateCleaningJobCustomer(id:int, customerId:int) : Task<bool>
    + {static} <<async>> UpdateCleaningJobCleaningOptions(id:int, cleaningJobOptions:List<CleaningJobOptionModel>) : Task<bool>
    + {static} <<async>> GetAvailableCleaners(cleaningJob:CleaningJobModel) : Task<List<StaffModel>>
    + {static} <<async>> UpdateCleaningJobStaff(id:int, staffIds:List<int>) : Task<bool>
}
@enduml
