@startuml
class CleaningJobModel {
    + Id : int <<get>> <<set>>
    + Address : string <<get>> <<set>>
    + CustomerId : int <<get>> <<set>>
    + StaffId : int <<get>> <<set>>
    + ExtraInformation : string <<get>> <<set>>
}
class "List`1"<T> {
}
CleaningJobModel o-> "StartDate" DateTime
CleaningJobModel o-> "EndDate" DateTime
CleaningJobModel o-> "StaffIds<int>" "List`1"
CleaningJobModel o-> "CleaningJobOptions<CleaningJobOptionModel>" "List`1"
@enduml
