@startuml
class AddStockPresenter {
    +  <<event>> NavigationRequest : EventHandler<NavigationEventArgs>? 
    + AddStockPresenter(view:IAddStockView, staff:StaffModel)
    + <<override>> CleanUp() : void
}
class "AddPresenter`2"<T1,T2> {
}
"AddPresenter`2" "<IAddStockView,StockModel>" <|-- AddStockPresenter
IChildPresenter <|-- AddStockPresenter
INavigatingPresenter <|-- AddStockPresenter
@enduml
