@startuml
class DisplayStockPresenter {
    +  <<event>> NavigationRequest : EventHandler<NavigationEventArgs>? 
    + DisplayStockPresenter(view:IDisplayStockView, staff:StaffModel)
    + <<async>> LoadData() : void
    + <<override>> CleanUp() : void
}
class "DisplayPresenter`3"<T1,T2,T3> {
}
"DisplayPresenter`3" "<IDisplayStockView,StockModel,DisplayStockModel>" <|-- DisplayStockPresenter
IChildPresenter <|-- DisplayStockPresenter
INavigatingPresenter <|-- DisplayStockPresenter
@enduml
