@startuml
class ManageStockWarningPresenter {
    +  <<event>> DetailsChanged : EventHandler? 
    + ManageStockWarningPresenter(view:IManageStockWarningView)
    + HighQuantity : int <<get>> <<set>>
    + LowQuantity : int <<get>> <<set>>
    + CanExit() : bool
}
class "BasePresenter`1"<T> {
}
"BasePresenter`1" "<IManageStockWarningView>" <|-- ManageStockWarningPresenter
INotifyingChildPresenter <|-- ManageStockWarningPresenter
@enduml
