@startuml
class DisplayCustomerPresenter {
    +  <<event>> NavigationRequest : EventHandler<NavigationEventArgs>? 
    + DisplayCustomerPresenter(view:IDisplayCustomerView)
    + <<async>> LoadData() : void
    + <<override>> CleanUp() : void
}
class "DisplayPresenter`3"<T1,T2,T3> {
}
"DisplayPresenter`3" "<IDisplayCustomerView,CustomerModel,DisplayCustomerModel>" <|-- DisplayCustomerPresenter
IChildPresenter <|-- DisplayCustomerPresenter
INavigatingPresenter <|-- DisplayCustomerPresenter
@enduml
