@startuml
class ManageCustomerPersonalDetailsPresenter {
    +  <<event>> DetailsChanged : EventHandler? 
    + ManageCustomerPersonalDetailsPresenter(view:IManageCustomerPersonalDetailsView)
    + Forename : string <<get>> <<set>>
    + ForenameValid : bool <<get>>
    + Surname : string <<get>> <<set>>
    + SurnameValid : bool <<get>>
    + Archived : bool <<get>> <<set>>
    + CanExit() : bool
    + <<override>> CleanUp() : void
}
class "BasePresenter`1"<T> {
}
"BasePresenter`1" "<IManageCustomerPersonalDetailsView>" <|-- ManageCustomerPersonalDetailsPresenter
INotifyingChildPresenter <|-- ManageCustomerPersonalDetailsPresenter
IChildPresenter <|-- ManageCustomerPersonalDetailsPresenter
@enduml
