@startuml
class ControlExtensions <<static>> {
    + {static} ExecuteRecursive(control:Control, a:Action<Control>) : void
    + {static} SetFontName(control:Control, fontName:string) : void
}
@enduml
