@startuml
class IconTheme {
}
IconTheme --> "Current" IconTheme
IconTheme o-> "Dark" IconTheme
IconTheme o-> "Light" IconTheme
IconTheme o-> "Logo" Image
IconTheme o-> "Brightness" Image
IconTheme o-> "Moon" Image
IconTheme o-> "Eye" Image
IconTheme o-> "EyeCrossed" Image
IconTheme o-> "Settings" Image
IconTheme o-> "BackArrow" Image
IconTheme o-> "ForwardArrow" Image
IconTheme o-> "DoubleBackArrow" Image
IconTheme o-> "DoubleForwardArrow" Image
IconTheme o-> "Plus" Image
IconTheme o-> "Minus" Image
IconTheme o-> "Navigation" Image
IconTheme o-> "Search" Image
IconTheme o-> "Cross" Image
IconTheme o-> "Tick" Image
IconTheme o-> "Edit" Image
IconTheme o-> "Delete" Image
IconTheme o-> "Archive" Image
IconTheme o-> "Restore" Image
IconTheme o-> "ClosedBox" Image
IconTheme o-> "OpenBox" Image
IconTheme o-> "Download" Image
@enduml
