@startuml
class Theme {
    + Theme(theme:AppearanceTheme?, showToolTips:bool?, fontName:string?)
    + Theme()
    + {static}  <<event>> AppearanceThemeChanged : Action? 
    + {static}  <<event>> ShowToolTipsChanged : Action? 
    + ShowToolTips : bool <<get>> <<set>>
    + {static}  <<event>> FontNameChanged : Action? 
    + FontName : string <<get>> <<set>>
    + IsDarkMode : bool <<get>>
    + {static} ToggleTheme() : void
}
enum AppearanceTheme {
    Dark,
    Light,
}
Theme --> "Current" Theme
Theme --> "AppearanceTheme" AppearanceTheme
Theme o-> "JsonSettings" JsonSerializerSettings
@enduml
