@startuml
class BookCleaningJobView <<partial>> {
    +  <<event>> Search : EventHandler? 
    +  <<event>> SortRequested : EventHandler<SortRequestEventArgs>? 
    +  <<event>> DateChanged : EventHandler? 
    +  <<event>> Add : EventHandler? 
    +  <<event>> Edit : EventHandler? 
    +  <<event>> View : EventHandler? 
    +  <<event>> Delete : EventHandler? 
    + BookCleaningJobView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + SearchText : string <<get>> <<set>>
    + DataGridText : string <<get>> <<set>>
    + DisplayItems(items:BindingList<DisplayCleaningJobModel>) : void
    + AddEnabled : bool <<get>> <<set>>
    + DeleteEnabled : bool <<get>> <<set>>
    + ViewMode : bool <<get>> <<set>>
    + DisableAll() : void
    + EnableAll() : void
    + ShowMessageBox(text:string, caption:string, buttons:MessageBoxButtons) : DialogResult
    + CleanUp() : void
}
Form <|-- BookCleaningJobView
IThemeable <|-- BookCleaningJobView
IBookCleaningJobView <|-- BookCleaningJobView
BookCleaningJobView --> "SelectedItem" DisplayCleaningJobModel
BookCleaningJobView --> "Date" DateTime
@enduml
