@startuml
class DisplayCleaningJobModel {
    + Id : int <<get>> <<set>>
    + Times : string <<get>> <<set>>
    + Address : string <<get>> <<set>>
    + DisplayCleaningJobModel(model:CleaningJobModel)
    +  <<event>> PropertyChanged : PropertyChangedEventHandler? 
}
INotifyPropertyChanged <|-- DisplayCleaningJobModel
@enduml
