@startuml
interface ISelectCleaningJobCustomerView {
    +  <<event>> Search : EventHandler? 
    +  <<event>> SelectionChanged : EventHandler? 
    +  <<event>> SortRequested : EventHandler<SortRequestEventArgs>? 
    + DisableAll() : void
    + EnableAll() : void
    + DataGridText : string <<get>> <<set>>
    + SetSelectedItemId(id:int) : void
}
class "IDisplayView`1"<T> {
}
"IDisplayView`1" "<DisplayCustomerModel>" <|-- ISelectCleaningJobCustomerView
IChildView <|-- ISelectCleaningJobCustomerView
ISelectCleaningJobCustomerView --> "SelectedItem" DisplayCustomerModel
@enduml
