@startuml
class ManageCleaningJobOptionsView <<partial>> {
    +  <<event>> QuantityChanged : EventHandler? 
    +  <<event>> Search : EventHandler? 
    +  <<event>> SelectionChanged : EventHandler? 
    +  <<event>> SortRequested : EventHandler<SortRequestEventArgs>? 
    + ManageCleaningJobOptionsView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + SearchText : string <<get>> <<set>>
    + DataGridText : string <<get>> <<set>>
    + CleaningOptionName : string <<get>> <<set>>
    + CleaningOptionDescription : string <<get>> <<set>>
    + Quantity : int <<get>> <<set>>
    + Subtotal : decimal <<set>>
    + Total : decimal <<set>>
    + Editable : bool <<get>> <<set>>
    + DisplayItems(items:BindingList<DisplayCleaningJobOptionModel>) : void
    + DisableAll() : void
    + EnableAll() : void
    + CleanUp() : void
}
class "IDisplayView`1"<T> {
}
Form <|-- ManageCleaningJobOptionsView
"IDisplayView`1" "<DisplayCleaningJobOptionModel>" <|-- ManageCleaningJobOptionsView
IChildView <|-- ManageCleaningJobOptionsView
IThemeable <|-- ManageCleaningJobOptionsView
IManageCleaningJobOptionsView <|-- ManageCleaningJobOptionsView
ManageCleaningJobOptionsView --> "SelectedItem" DisplayCleaningJobOptionModel
@enduml
