@startuml
class CornerRadiiFConverter {
    + <<override>> CanConvertFrom(context:ITypeDescriptorContext?, sourceType:Type) : bool
    + <<override>> CanConvertTo(context:ITypeDescriptorContext?, destinationType:Type?) : bool
    + <<override>> ConvertFrom(context:ITypeDescriptorContext?, culture:CultureInfo?, value:object) : object?
    + <<override>> ConvertTo(context:ITypeDescriptorContext?, culture:CultureInfo?, value:object?, destinationType:Type) : object?
    + <<override>> CreateInstance(context:ITypeDescriptorContext?, propertyValues:IDictionary) : object
    + <<override>> GetCreateInstanceSupported(context:ITypeDescriptorContext?) : bool
    + <<override>> GetProperties(context:ITypeDescriptorContext?, value:object, attributes:Attribute[]?) : PropertyDescriptorCollection
    + <<override>> GetPropertiesSupported(context:ITypeDescriptorContext?) : bool
}
TypeConverter <|-- CornerRadiiFConverter
@enduml
