@startuml
struct CornerRadiiF {
    + CornerRadiiF(all:float)
    + CornerRadiiF(topLeft:float, topRight:float, bottomLeft:float, bottomRight:float)
    + TopLeft : float <<readonly get>> <<set>>
    + TopRight : float <<readonly get>> <<set>>
    + BottomLeft : float <<readonly get>> <<set>>
    + BottomRight : float <<readonly get>> <<set>>
    + All : float <<readonly get>> <<set>>
    + Equals(other:CornerRadiiF) : bool
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<CornerRadiiF>" <|-- CornerRadiiF
CornerRadiiF o-> "Empty" CornerRadiiF
@enduml
