@startuml
class CustomNumericUpDown <<partial>> {
    +  <<event>> ValueChanged : EventHandler? 
    + CustomNumericUpDown()
    + Theme() : void
    + Minimum : int <<get>> <<set>>
    + Maximum : int <<get>> <<set>>
    + Value : int <<get>> <<set>>
    + Increment(i:int) : void
    + Decrement(i:int) : void
    + SetToolTipVisibility() : void
    + SetFont() : void
}
UserControl <|-- CustomNumericUpDown
IThemeable <|-- CustomNumericUpDown
@enduml
