@startuml
class CustomButton <<partial>> {
    + <<new>> Text : string <<get>> <<set>>
    + <<new>>  <<event>> EnabledChanged : EventHandler? 
    + <<new>> Enabled : bool <<get>> <<set>>
}
enum CustomButtonAlign {
    TopLeft,
    TopCenter,
    TopRight,
    MiddleLeft,
    MiddleCenter,
    MiddleRight,
    BottomLeft,
    BottomCenter,
    BottomRight,
    Point,
}
enum ButtonState {
    Normal,
    Clicked,
    Hover,
}
CustomButton --> "BackColor" Color
CustomButton --> "BorderColor" Color
CustomButton --> "HoverColor" Color
CustomButton --> "HoverBorderColor" Color
CustomButton --> "ClickedColor" Color
CustomButton --> "ClickedBorderColor" Color
CustomButton --> "DisabledColor" Color
CustomButton --> "DisabledBorderColor" Color
CustomButton --> "TextAlign" CustomButtonAlign
CustomButton --> "TextPosition" Point
CustomButton --> "Image" Image
CustomButton --> "ImageRectangle" Rectangle
CustomButton +-- ButtonState
@enduml
