@startuml
class DateInput <<partial>> {
    +  <<event>> DateTextChanged : EventHandler? 
    + DayText : string <<get>>
    + MonthText : string <<get>>
    + YearText : string <<get>>
    + Day : int? <<get>> <<set>>
    + DateValid : bool <<get>>
    + Month : int? <<get>> <<set>>
    + Year : int? <<get>> <<set>>
    + BorderThickness : float <<get>> <<set>>
    + NullValid : bool <<get>> <<set>>
    + ShowPlaceholder : bool <<get>> <<set>>
    + <<new>> Enabled : bool <<get>> <<set>>
    + DayToolTip : string <<get>> <<set>>
    + MonthToolTip : string <<get>> <<set>>
    + YearToolTip : string <<get>> <<set>>
    + ToolTipsActive : bool <<get>> <<set>>
    + ReadOnly : bool <<get>> <<set>>
}
enum DateErrorState {
    None,
    Incomplete,
    Invalid,
}
DateInput --> "MinDate" DateTime
DateInput --> "MaxDate" DateTime
DateInput --> "BackColor" Color
DateInput --> "ForeColor" Color
DateInput --> "PlaceholderTextColor" Color
DateInput --> "BorderColor" Color
DateInput --> "BorderErrorColor" Color
DateInput --> "Date" DateTime
DateInput --> "ErrorState" DateErrorState
DateInput +-- DateErrorState
@enduml
