@startuml
class TimeInput <<partial>> {
    + ReadOnly : bool <<get>> <<set>>
    + Hour : string <<get>> <<set>>
    + Minute : string <<get>> <<set>>
    + TimeValid : bool <<get>>
    + HourValid : bool <<get>>
    + MinuteValid : bool <<get>>
}
TimeInput --> "ForeColor" Color
TimeInput --> "BackColor" Color
TimeInput --> "Font" Font
TimeInput --> "PlaceholderColor" Color
TimeInput --> "BorderColor" Color
TimeInput --> "BorderErrorColor" Color
TimeInput --> "Time" TimeOnly
@enduml
