@startuml
class CustomerDAL <<static>> {
    + {static} <<async>> GetCustomers() : Task<List<CustomerModel>>
    + {static} <<async>> GetNonArchivedCustomers() : Task<List<CustomerModel>>
    + {static} <<async>> AddCustomer(customer:CustomerModel) : Task<bool>
    + {static} <<async>> UpdateCustomerArchived(id:int, archived:bool) : Task<bool>
    + {static} <<async>> UpdateCustomerPersonalDetails(id:int, forename:string, surname:string, archived:bool) : Task<bool>
    + {static} <<async>> UpdateCustomerContactDetails(id:int, phoneNumber:string, email:string, address:string) : Task<bool>
    + {static} <<async>> CustomerInFutureJob(id:int) : Task<bool>
}
@enduml
