@startuml
class CustomerModel {
    + Id : int <<get>> <<set>>
    + Forename : string <<get>> <<set>>
    + Surname : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + PhoneNumber : string <<get>> <<set>>
    + Address : string <<get>> <<set>>
    + Archived : bool <<get>> <<set>>
}
@enduml
