@startuml
class AddCustomerView <<partial>> {
    +  <<event>> Next : EventHandler? 
    +  <<event>> Previous : EventHandler? 
    +  <<event>> Done : EventHandler? 
    +  <<event>> Back : EventHandler? 
    + AddCustomerView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + DisplayChildView(childView:IChildView) : void
    + ShowMessageBox(text:string, caption:string, buttons:MessageBoxButtons) : DialogResult
    + IsLoading : bool <<get>> <<set>>
    + NextVisible : bool <<get>> <<set>>
    + PreviousVisible : bool <<get>> <<set>>
    + DoneVisible : bool <<get>> <<set>>
    + CleanUp() : void
}
Form <|-- AddCustomerView
IAddCustomerView <|-- AddCustomerView
IThemeable <|-- AddCustomerView
IChildView <|-- AddCustomerView
@enduml
