@startuml
class DisplayCustomerModel {
    + Id : int <<get>> <<set>>
    + Names : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + PhoneNumber : string <<get>> <<set>>
    + _archived : bool
    + Archived : bool <<get>> <<set>>
    + DisplayCustomerModel(model:CustomerModel)
    +  <<event>> PropertyChanged : PropertyChangedEventHandler? 
}
INotifyPropertyChanged <|-- DisplayCustomerModel
@enduml
