@startuml
class ManageCustomerContactDetailsView <<partial>> {
    +  <<event>> EmailChanged : EventHandler? 
    +  <<event>> PhoneNumberChanged : EventHandler? 
    +  <<event>> AddressChanged : EventHandler? 
    + ManageCustomerContactDetailsView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + Email : string <<get>> <<set>>
    + PhoneNumber : string <<get>> <<set>>
    + Address : string <<get>> <<set>>
    + ContactError : string <<get>> <<set>>
    + SetEmailBorderError(isError:bool) : void
    + SetPhoneNumberBorderError(isError:bool) : void
    + SetCharacterCount(number:int) : void
    + CleanUp() : void
}
Form <|-- ManageCustomerContactDetailsView
IManageCustomerContactDetailsView <|-- ManageCustomerContactDetailsView
IThemeable <|-- ManageCustomerContactDetailsView
@enduml
