@startuml
interface IAddView {
    +  <<event>> Next : EventHandler? 
    +  <<event>> Previous : EventHandler? 
    +  <<event>> Done : EventHandler? 
    + PreviousVisible : bool <<get>> <<set>>
    + NextVisible : bool <<get>> <<set>>
    + DoneVisible : bool <<get>> <<set>>
    + DisplayChildView(view:IChildView) : void
    + IsLoading : bool <<get>> <<set>>
    + ShowMessageBox(text:string, caption:string, buttons:MessageBoxButtons) : DialogResult
}
IView <|-- IAddView
@enduml
