@startuml
interface IChildView {
    +  <<event>> MouseWheel : MouseEventHandler? 
    + TopLevel : bool <<set>>
    + Width : int <<set>>
    + Height : int <<get>>
    + Show() : void
    + Text : string <<get>> <<set>>
}
IView <|-- IChildView
IChildView --> "Location" Point
IChildView --> "Anchor" AnchorStyles
IChildView --> "Dock" DockStyle
@enduml
