@startuml
interface IManageCleaningJobOptionsView {
    +  <<event>> Search : EventHandler? 
    +  <<event>> SelectionChanged : EventHandler? 
    +  <<event>> QuantityChanged : EventHandler? 
    +  <<event>> SortRequested : EventHandler<SortRequestEventArgs>? 
    + SearchText : string <<get>> <<set>>
    + DataGridText : string <<get>> <<set>>
    + CleaningOptionName : string <<get>> <<set>>
    + CleaningOptionDescription : string <<get>> <<set>>
    + Quantity : int <<get>> <<set>>
    + Subtotal : decimal <<set>>
    + Total : decimal <<set>>
    + Editable : bool <<get>> <<set>>
    + DisableAll() : void
    + EnableAll() : void
}
class "IDisplayView`1"<T> {
}
"IDisplayView`1" "<DisplayCleaningJobOptionModel>" <|-- IManageCleaningJobOptionsView
IManageCleaningJobOptionsView --> "SelectedItem" DisplayCleaningJobOptionModel
@enduml
