@startuml
interface ISaveCancelView {
    +  <<event>> Save : EventHandler? 
    +  <<event>> Cancel : EventHandler? 
    + SaveCancelVisible : bool <<set>>
    + IsLoading : bool <<get>> <<set>>
    + ShowMessageBox(text:string, caption:string, buttons:MessageBoxButtons) : DialogResult
}
IChildView <|-- ISaveCancelView
@enduml
