@startuml
class StockQuantityChange {
    + Id : int <<get>> <<init>>
    + Quantity : int <<get>> <<init>>
    + ReasonForQuantityChange : string <<get>> <<init>>
    + StockId : int <<get>> <<init>>
    + StockName : string <<get>> <<init>>
    + StockSKU : string <<get>> <<init>>
    + StockArchived : bool <<get>> <<init>>
    + StaffId : int <<get>> <<init>>
    + StaffForename : string <<get>> <<init>>
    + StaffSurname : string <<get>> <<init>>
    + StaffUsername : string <<get>> <<init>>
}
StockQuantityChange o-> "Date" DateTime
@enduml
