@startuml
abstract class "EditPresenter`2"<TView,TModel> {
    + EditPresenter(view:TView, model:TModel)
    + <<virtual>> CanExit() : bool
    + <<override>> CleanUp() : void
}
class "BasePresenter`1"<T> {
}
"BasePresenter`1" "<TView>" <|-- "EditPresenter`2"
@enduml
