@startuml
class AddStaffPresenter {
    +  <<event>> NavigationRequest : EventHandler<NavigationEventArgs>? 
    + AddStaffPresenter(view:IAddStaffView, staff:StaffModel)
    + <<override>> CleanUp() : void
}
class "AddPresenter`2"<T1,T2> {
}
"AddPresenter`2" "<IAddStaffView,StaffModel>" <|-- AddStaffPresenter
IChildPresenter <|-- AddStaffPresenter
INavigatingPresenter <|-- AddStaffPresenter
@enduml
