@startuml
class DisplayStaffPresenter {
    +  <<event>> NavigationRequest : EventHandler<NavigationEventArgs>? 
    + DisplayStaffPresenter(view:IDisplayStaffView, staff:StaffModel)
    + <<async>> LoadData() : void
    + <<override>> CleanUp() : void
}
class "DisplayPresenter`3"<T1,T2,T3> {
}
"DisplayPresenter`3" "<IDisplayStaffView,StaffModel,DisplayStaffModel>" <|-- DisplayStaffPresenter
IChildPresenter <|-- DisplayStaffPresenter
INavigatingPresenter <|-- DisplayStaffPresenter
@enduml
