@startuml
class EditStaffPresenter {
    +  <<event>> NavigationRequest : EventHandler<NavigationEventArgs>? 
    + EditStaffPresenter(view:IEditStaffView, model:StaffModel, staff:StaffModel)
    + <<override>> CleanUp() : void
}
class "ParentEditPresenter`2"<T1,T2> {
}
"ParentEditPresenter`2" "<IEditStaffView,StaffModel>" <|-- EditStaffPresenter
IChildPresenter <|-- EditStaffPresenter
INavigatingPresenter <|-- EditStaffPresenter
@enduml
