@startuml
class ManageStaffContactDetailsPresenter {
    +  <<event>> DetailsChanged : EventHandler? 
    + ManageStaffContactDetailsPresenter(view:IManageStaffContactDetailsView)
    + Email : string <<get>> <<set>>
    + EmailValid : bool <<get>>
    + PhoneNumber : string <<get>> <<set>>
    + PhoneNumberValid : bool <<get>>
    + Address : string <<get>> <<set>>
    + CanExit() : bool
    + <<override>> CleanUp() : void
}
class "BasePresenter`1"<T> {
}
"BasePresenter`1" "<IManageStaffContactDetailsView>" <|-- ManageStaffContactDetailsPresenter
INotifyingChildPresenter <|-- ManageStaffContactDetailsPresenter
@enduml
