@startuml
class ManageStaffPasswordPresenter {
    + ManageStaffPasswordPresenter(view:IManageStaffPasswordView)
    + Password : string <<get>> <<set>>
    + ConfirmPassword : string <<get>> <<set>>
    + PasswordValid : bool <<get>>
    + <<override>> CleanUp() : void
}
class "BasePresenter`1"<T> {
}
"BasePresenter`1" "<IManageStaffPasswordView>" <|-- ManageStaffPasswordPresenter
@enduml
