@startuml
class ManageStaffCredentialsPresenter {
    +  <<event>> DetailsChanged : EventHandler? 
    +  <<event>> ValidateUsernameRequest : EventHandler<ValidationRequestEventArgs<string>>? 
    + ManageStaffCredentialsPresenter(view:IManageStaffCredentialsView)
    + SetSuggestedUsername(suggestedUsername:string) : string
    + Username : string <<get>> <<set>>
    + UsernameValid : bool <<get>>
    + CanExit() : bool
    + <<override>> CleanUp() : void
}
class "BasePresenter`1"<T> {
}
"BasePresenter`1" "<IManageStaffCredentialsView>" <|-- ManageStaffCredentialsPresenter
IChildPresenter <|-- ManageStaffCredentialsPresenter
INotifyingChildPresenter <|-- ManageStaffCredentialsPresenter
ManageStaffCredentialsPresenter --> "PrivilegeLevel" PrivilegeLevel
@enduml
