@startuml
class ManageStaffAppearanceSettingsPresenter {
    +  <<event>> DetailsChanged : EventHandler? 
    + ManageStaffAppearanceSettingsPresenter(view:IManageStaffAppearanceSettingsView)
    + DarkMode : bool <<get>> <<set>>
    + ShowToolTips : bool <<get>> <<set>>
    + FontName : string <<get>> <<set>>
    + CanExit() : bool
}
class "BasePresenter`1"<T> {
}
"BasePresenter`1" "<IManageStaffAppearanceSettingsView>" <|-- ManageStaffAppearanceSettingsPresenter
INotifyingChildPresenter <|-- ManageStaffAppearanceSettingsPresenter
IChildPresenter <|-- ManageStaffAppearanceSettingsPresenter
@enduml
