@startuml
class AddCleaningJobOptionPresenter {
    +  <<event>> NavigationRequest : EventHandler<NavigationEventArgs>? 
    + AddCleaningJobOptionPresenter(view:IAddCleaningJobOptionView)
    + <<override>> CleanUp() : void
}
class "AddPresenter`2"<T1,T2> {
}
"AddPresenter`2" "<IAddCleaningJobOptionView,CleaningJobOptionModel>" <|-- AddCleaningJobOptionPresenter
IChildPresenter <|-- AddCleaningJobOptionPresenter
INavigatingPresenter <|-- AddCleaningJobOptionPresenter
@enduml
