@startuml
class DisplayCleaningJobOptionPresenter {
    +  <<event>> NavigationRequest : EventHandler<NavigationEventArgs>? 
    + DisplayCleaningJobOptionPresenter(view:IDisplayCleaningJobOptionView)
    + <<override>> CleanUp() : void
}
class "DisplayPresenter`3"<T1,T2,T3> {
}
"DisplayPresenter`3" "<IDisplayCleaningJobOptionView,CleaningJobOptionModel,DisplayCleaningJobOptionModel>" <|-- DisplayCleaningJobOptionPresenter
IChildPresenter <|-- DisplayCleaningJobOptionPresenter
INavigatingPresenter <|-- DisplayCleaningJobOptionPresenter
@enduml
