@startuml
class EditCleaningJobOptionPresenter {
    +  <<event>> NavigationRequest : EventHandler<NavigationEventArgs>? 
    + EditCleaningJobOptionPresenter(view:IEditCleaningJobOptionView, model:CleaningJobOptionModel)
    + <<override>> CleanUp() : void
}
class "ParentEditPresenter`2"<T1,T2> {
}
"ParentEditPresenter`2" "<IEditCleaningJobOptionView,CleaningJobOptionModel>" <|-- EditCleaningJobOptionPresenter
IChildPresenter <|-- EditCleaningJobOptionPresenter
INavigatingPresenter <|-- EditCleaningJobOptionPresenter
@enduml
