@startuml
!include .\\AppContext.puml
!include .\\ApplicationStartManager.puml
!include .\\Program.puml
!include .\\CustomControls\CornerRadiiF.puml
!include .\\CustomControls\CornerRadiiFConverter.puml
!include .\\CustomControls\CustomButton.puml
!include .\\CustomControls\CustomButton.Properties.puml
!include .\\CustomControls\CustomComboBox.puml
!include .\\CustomControls\CustomControlHelpers.puml
!include .\\CustomControls\CustomMessageBox.puml
!include .\\CustomControls\CustomMessageBoxView.puml
!include .\\CustomControls\CustomMessageBoxView.Designer.puml
!include .\\CustomControls\CustomMonthCalendar.puml
!include .\\CustomControls\CustomMonthCalendar.Designer.puml
!include .\\CustomControls\CustomMonthCalendar.Properties.puml
!include .\\CustomControls\CustomNumericUpDown.puml
!include .\\CustomControls\CustomNumericUpDown.Designer.puml
!include .\\CustomControls\CustomPanel.puml
!include .\\CustomControls\CustomRadioButton.puml
!include .\\CustomControls\CustomScrollBar.puml
!include .\\CustomControls\CustomScrollBar.Properties.puml
!include .\\CustomControls\CustomTextBox.puml
!include .\\CustomControls\CustomTextBox.Designer.puml
!include .\\CustomControls\CustomTextBox.Properties.puml
!include .\\CustomControls\DateInput.puml
!include .\\CustomControls\DateInput.Designer.puml
!include .\\CustomControls\DateInput.Properties.puml
!include .\\CustomControls\ImprovedTextBox.puml
!include .\\CustomControls\Paginator.puml
!include .\\CustomControls\Paginator.Designer.puml
!include .\\CustomControls\TimeInput.puml
!include .\\CustomControls\TimeInput.Designer.puml
!include .\\CustomControls\TimeInput.Properties.puml
!include .\\Factory\CleaningJobFactory.puml
!include .\\Factory\CleaningJobOptionFactory.puml
!include .\\Factory\CustomerFactory.puml
!include .\\Factory\ReportFactory.puml
!include .\\Factory\SignInFactory.puml
!include .\\Factory\StaffFactory.puml
!include .\\Interfaces\IAddView.puml
!include .\\Interfaces\IChildView.puml
!include .\\Interfaces\IDisplayView.puml
!include .\\Interfaces\IEditView.puml
!include .\\Interfaces\IManageCleaningJobOptionsView.puml
!include .\\Interfaces\ISaveCancelView.puml
!include .\\Interfaces\IView.puml
!include .\\Model\CryptographyManager.puml
!include .\\Presenter\BasePresenter.puml
!include .\\Presenter\DisplayPresenter.puml
!include .\\Presenter\EditPresenter.puml
!include .\\Presenter\FilteringDisplayPresenter.puml
!include .\\Presenter\IChildPresenter.puml
!include .\\Presenter\ICleanable.puml
!include .\\Presenter\INavigatingPresenter.puml
!include .\\Presenter\INotifyingChildPresenter.puml
!include .\\Presenter\ISearch.puml
!include .\\Presenter\NavigationEventArgs.puml
!include .\\Presenter\ParentAddPresenter.puml
!include .\\Presenter\ParentEditPresenter.puml
!include .\\Presenter\ValidationRequestEventArgs.puml
!include .\\Properties\Resources.Designer.puml
!include .\\Theming\ColorScheme.puml
!include .\\Theming\IconTheme.puml
!include .\\Theming\IThemeable.puml
!include .\\Theming\Theme.puml
!include .\\Theming\ThemingExtenders.puml
!include .\\User Controls\ToggleButton.puml
!include .\\User Controls\ToggleEventArgs.puml
!include .\\User Controls\TopBar.puml
!include .\\User Controls\TopBar.Designer.puml
!include .\\View\SortRequestEventArgs.puml
!include .\\_Helpers\ControlExtensions.puml
!include .\\_Helpers\ControlHelpers.puml
!include .\\_Helpers\GeneralHelpers.puml
!include .\\_Helpers\Validators.puml
!include .\\Interfaces\CleaningJob\IBookCleaningJobView.puml
!include .\\Interfaces\CleaningJob\IEditCleaningJobView.puml
!include .\\Interfaces\CleaningJob\IManageCleaningJobDuration.puml
!include .\\Interfaces\CleaningJob\IManageCleaningJobOptionDetails.puml
!include .\\Interfaces\CleaningJob\ISelectCleaningJobOptionsView.puml
!include .\\Interfaces\CleaningJob\ISelectCleaningJobStaffView.puml
!include .\\Interfaces\CleaningJobOption\IAddCleaningJobOptionView.puml
!include .\\Interfaces\CleaningJobOption\IDisplayCleaningJobOptionView.puml
!include .\\Interfaces\CleaningJobOption\IEditCleaningJobOptionView.puml
!include .\\Interfaces\CleaningJobOption\IManageCleaningJobOptionView.puml
!include .\\Interfaces\Customer\IAddCustomerView.puml
!include .\\Interfaces\Customer\IDisplayCustomerView.puml
!include .\\Interfaces\Customer\IEditCustomerView.puml
!include .\\Interfaces\Customer\IManageCustomerContactDetailsView.puml
!include .\\Interfaces\Customer\IManageCustomerPersonalDetailsView.puml
!include .\\Interfaces\LoginAttempt\IDisplayLoginAttemptView.puml
!include .\\Interfaces\Report\IReportView.puml
!include .\\Interfaces\SignIn\IDashboardView.puml
!include .\\Interfaces\SignIn\IMasterView.puml
!include .\\Interfaces\SignIn\ISignInView.puml
!include .\\Interfaces\SignIn\ISplashView.puml
!include .\\Model\CleaningJob\CleaningJobDAL.puml
!include .\\Model\CleaningJob\CleaningJobModel.puml
!include .\\Model\CleaningJobOption\CleaningJobOptionDAL.puml
!include .\\Model\CleaningJobOption\CleaningJobOptionModel.puml
!include .\\Model\Customer\CustomerDAL.puml
!include .\\Model\Customer\CustomerModel.puml
!include .\\Model\LoginAttempt\LoginAttemptDAL.puml
!include .\\Model\LoginAttempt\LoginAttemptModel.puml
!include .\\Model\Reports\ReportGenerator.puml
!include .\\Model\Reports\StaffReportGenerator.puml
!include .\\Model\Reports\StockReportGenerator.puml
!include .\\Model\Staff\PrivilegeLevel.puml
!include .\\Model\Staff\StaffDAL.puml
!include .\\Model\Staff\StaffModel.puml
!include .\\Model\Stock\StockDAL.puml
!include .\\Model\Stock\StockModel.puml
!include .\\Model\Stock\StockQuantityChange.puml
!include .\\Presenter\CleaningJob\BookCleaningJobPresenter.puml
!include .\\Presenter\CleaningJob\EditCleaningJobPresenter.puml
!include .\\Presenter\CleaningJob\ManageCleaningJobDetailsPresenter.puml
!include .\\Presenter\CleaningJob\ManageCleaningJobDurationPresenter.puml
!include .\\Presenter\CleaningJob\ManageCleaningJobOptionsPresenter.puml
!include .\\Presenter\CleaningJob\SelectCleaningJobCustomerPresenter.puml
!include .\\Presenter\CleaningJob\SelectCleaningJobOptionsPresenter.puml
!include .\\Presenter\CleaningJob\SelectCleaningJobStaffPresenter.puml
!include .\\Presenter\CleaningJobOption\AddCleaningJobOptionPresenter.puml
!include .\\Presenter\CleaningJobOption\DisplayCleaningJobOptionPresenter.puml
!include .\\Presenter\CleaningJobOption\EditCleaningJobOptionPresenter.puml
!include .\\Presenter\CleaningJobOption\ManageJobCleaningOptionPresenter.puml
!include .\\Presenter\Customer\AddCustomerPresenter.puml
!include .\\Presenter\Customer\DisplayCustomerPresenter.puml
!include .\\Presenter\Customer\EditCustomerPresenter.puml
!include .\\Presenter\Customer\ManageCustomerContactDetailPresenter.puml
!include .\\Presenter\Customer\ManageCustomerPersonalDetailsPresenter.puml
!include .\\Presenter\LoginAttempt\DisplayLoginAttemptPresenter.puml
!include .\\Presenter\Report\ReportPresenter.puml
!include .\\Presenter\SignIn\DashboardPresenter.puml
!include .\\Presenter\SignIn\MasterPresenter.puml
!include .\\Presenter\SignIn\SignInPresenter.puml
!include .\\Presenter\SignIn\SplashPresenter.puml
!include .\\Presenter\Staff\ChangeStaffPasswordPresenter.puml
!include .\\User Controls\CRUD\AddEditArchiveSearchBar.puml
!include .\\User Controls\CRUD\AddEditArchiveSearchBar.Designer.puml
!include .\\User Controls\CRUD\AddEditDeleteSearchBar.puml
!include .\\User Controls\CRUD\AddEditDeleteSearchBar.Designer.puml
!include .\\User Controls\CRUD\PreviousNextDoneBar.puml
!include .\\User Controls\CRUD\PreviousNextDoneBar.Designer.puml
!include .\\User Controls\CRUD\SearchBar.puml
!include .\\User Controls\CRUD\SearchBar.Designer.puml
!include .\\User Controls\CRUD\ViewSearchBar.puml
!include .\\User Controls\CRUD\ViewSearchBar.Designer.puml
!include .\\User Controls\Menu\MenuButton.puml
!include .\\User Controls\Menu\MenuButton.Designer.puml
!include .\\User Controls\Menu\MenuDropdown.puml
!include .\\User Controls\Menu\MenuDropdown.Designer.puml
!include .\\User Controls\Menu\MenuToggleButton.puml
!include .\\User Controls\Menu\MenuToggleButton.Designer.puml
!include .\\User Controls\Menu\SideMenu.puml
!include .\\User Controls\Menu\SideMenu.Designer.puml
!include .\\User Controls\Menu\TopMenu.puml
!include .\\User Controls\Menu\TopMenu.Designer.puml
!include .\\User Controls\Menu\TopMenuItem.puml
!include .\\User Controls\Menu\TopMenuItem.Designer.puml
!include .\\User Controls\Settings\ApproveChangesBar.puml
!include .\\User Controls\Settings\ApproveChangesBar.Designer.puml
!include .\\View\CleaningJob\AddCleaningJobView.puml
!include .\\View\CleaningJob\AddCleaningJobView.Designer.puml
!include .\\View\CleaningJob\BookCleaningJobView.puml
!include .\\View\CleaningJob\BookCleaningJobView.Designer.puml
!include .\\View\CleaningJob\DisplayCleaningJobModel.puml
!include .\\View\CleaningJob\EditCleaningJobView.puml
!include .\\View\CleaningJob\EditCleaningJobView.Designer.puml
!include .\\View\CleaningJob\ISelectCleaningJobCustomerView.puml
!include .\\View\CleaningJob\ManageCleaningJobDetailsView.puml
!include .\\View\CleaningJob\ManageCleaningJobDetailsView.Designer.puml
!include .\\View\CleaningJob\ManageCleaningJobDurationView.puml
!include .\\View\CleaningJob\ManageCleaningJobDurationView.Designer.puml
!include .\\View\CleaningJob\ManageCleaningJobOptionsView.puml
!include .\\View\CleaningJob\ManageCleaningJobOptionsView.Designer.puml
!include .\\View\CleaningJob\SelectCleaningJobCustomerView.puml
!include .\\View\CleaningJob\SelectCleaningJobCustomerView.Designer.puml
!include .\\View\CleaningJob\SelectCleaningJobOptionsView.puml
!include .\\View\CleaningJob\SelectCleaningJoboptionsView.Designer.puml
!include .\\View\CleaningJob\SelectCleaningJobStaffView.puml
!include .\\View\CleaningJob\SelectCleaningJobStaffView.Designer.puml
!include .\\View\CleaningJobOptions\AddCleaningJobOptionView.puml
!include .\\View\CleaningJobOptions\AddCleaningJobOptionView.Designer.puml
!include .\\View\CleaningJobOptions\DisplayCleaningJobOptionModel.puml
!include .\\View\CleaningJobOptions\DisplayCleaningJobOptionView.puml
!include .\\View\CleaningJobOptions\DisplayCleaningJobOptionView.Designer.puml
!include .\\View\CleaningJobOptions\EditCleaningJobOptionView.puml
!include .\\View\CleaningJobOptions\EditCleaningJobOptionView.Designer.puml
!include .\\View\CleaningJobOptions\ManageCleaningJobOptionView.puml
!include .\\View\CleaningJobOptions\ManageCleaningJobOptionView.Designer.puml
!include .\\View\Customer\AddCustomerView.puml
!include .\\View\Customer\AddCustomerView.Designer.puml
!include .\\View\Customer\DisplayCustomerModel.puml
!include .\\View\Customer\DisplayCustomerView.puml
!include .\\View\Customer\DisplayCustomerView.Designer.puml
!include .\\View\Customer\EditCustomerView.puml
!include .\\View\Customer\EditCustomerView.Designer.puml
!include .\\View\Customer\ManageCustomerContactDetailsView.puml
!include .\\View\Customer\ManageCustomerContactDetailsView.Designer.puml
!include .\\View\Customer\ManageCustomerPersonalDetailsView.puml
!include .\\View\Customer\ManageCustomerPersonalDetailsView.Designer.puml
!include .\\View\LoginAttempt\DisplayLoginAttemptModel.puml
!include .\\View\LoginAttempt\DisplayLoginAttemptView.puml
!include .\\View\LoginAttempt\DisplayLoginAttemptview.Designer.puml
!include .\\View\Report\ReportView.puml
!include .\\View\Report\ReportView.Designer.puml
!include .\\View\SignIn\DashboardView.puml
!include .\\View\SignIn\DashboardView.Designer.puml
!include .\\View\SignIn\MasterView.puml
!include .\\View\SignIn\MasterView.Designer.puml
!include .\\View\SignIn\SignInView.puml
!include .\\View\SignIn\SignInView.Designer.puml
!include .\\View\SignIn\SplashView.puml
!include .\\View\SignIn\SplashView.Designer.puml
!include .\\View\SignIn\TestView.puml
!include .\\View\SignIn\TestView.Designer.puml
!include .\\Interfaces\Staff\Settings\IAppearanceSettings.puml
!include .\\Interfaces\Staff\Settings\IContactDetailsSettings.puml
!include .\\Interfaces\Staff\Settings\IEmergencyContactSettings.puml
!include .\\Interfaces\Staff\Settings\IPersonalInformationSettings.puml
!include .\\Interfaces\Staff\Settings\ISecuritySettingsView.puml
!include .\\Interfaces\Staff\StaffManagement\IAddStaffView.puml
!include .\\Interfaces\Staff\StaffManagement\IChangePasswordView.puml
!include .\\Interfaces\Staff\StaffManagement\IDisplayStaffView.puml
!include .\\Interfaces\Staff\StaffManagement\IEditStaffView.puml
!include .\\Interfaces\Staff\StaffManagement\IManageStaffAppearanceSettingsView.puml
!include .\\Interfaces\Staff\StaffManagement\IManageStaffContactDetailsView.puml
!include .\\Interfaces\Staff\StaffManagement\IManageStaffCredentialsView.puml
!include .\\Interfaces\Staff\StaffManagement\IManageStaffEmergencyContactDetailsView.puml
!include .\\Interfaces\Staff\StaffManagement\IManageStaffPasswordView.puml
!include .\\Interfaces\Staff\StaffManagement\IManageStaffPersonalInformationView.puml
!include .\\Interfaces\Stock\StockManagement\IAddStockView.puml
!include .\\Interfaces\Stock\StockManagement\IDisplayStockView.puml
!include .\\Interfaces\Stock\StockManagement\IEditStockView.puml
!include .\\Interfaces\Stock\StockManagement\IManageStockDetailsView.puml
!include .\\Interfaces\Stock\StockManagement\IManageStockQuantityView.puml
!include .\\Interfaces\Stock\StockManagement\IManageStockWarningView.puml
!include .\\Interfaces\Stock\StockQuantityChanges\IDisplayStockQuantityChangesView.puml
!include .\\Interfaces\Stock\StockQuantityChanges\IViewStockQuantityChangeView.puml
!include .\\obj\Debug\net8.0-windows\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0-windows\a2-coursework.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\a2-coursework.GlobalUsings.g.puml
!include .\\Presenter\Staff\Settings\AppearanceSettingsPresenter.puml
!include .\\Presenter\Staff\Settings\ContactDetailsSettingsPresenter.puml
!include .\\Presenter\Staff\Settings\EmergencyContactSettingsPresenter.puml
!include .\\Presenter\Staff\Settings\ManageStaffCredentialsPresenter.puml
!include .\\Presenter\Staff\Settings\PersonalInformationSettingsPresenter.puml
!include .\\Presenter\Staff\Settings\SecuritySettingsPresenter.puml
!include .\\Presenter\Staff\Settings\SettingsPresenter.puml
!include .\\Presenter\Staff\StaffManagement\AddStaffPresenter.puml
!include .\\Presenter\Staff\StaffManagement\DisplayStaffPresenter.puml
!include .\\Presenter\Staff\StaffManagement\EditStaffPresenter.puml
!include .\\Presenter\Staff\StaffManagement\ManageStaffAppearanceSettingsPresenter.puml
!include .\\Presenter\Staff\StaffManagement\ManageStaffContactDetailsPresenter.puml
!include .\\Presenter\Staff\StaffManagement\ManageStaffCredentialsPresenter.puml
!include .\\Presenter\Staff\StaffManagement\ManageStaffEmergencyContactDetailsPresenter.puml
!include .\\Presenter\Staff\StaffManagement\ManageStaffPasswordPresenter.puml
!include .\\Presenter\Staff\StaffManagement\ManageStaffPersonalDetailsPresenter.puml
!include .\\Presenter\Stock\StockManagement\AddStockPresenter.puml
!include .\\Presenter\Stock\StockManagement\DisplayStockPresenter.puml
!include .\\Presenter\Stock\StockManagement\EditStockPresenter.puml
!include .\\Presenter\Stock\StockManagement\ManageStockDetailsPresenter.puml
!include .\\Presenter\Stock\StockManagement\ManageStockQuantityPresenter.puml
!include .\\Presenter\Stock\StockManagement\ManageStockWarningPresenter.puml
!include .\\Presenter\Stock\StockQuantityChanges\DisplayStockQuantityChangesPresenter.puml
!include .\\Presenter\Stock\StockQuantityChanges\ViewStockQuantityChangePresenter.puml
!include .\\View\Staff\Settings\AppearanceSettingsView.puml
!include .\\View\Staff\Settings\AppearanceSettingsView.Designer.puml
!include .\\View\Staff\Settings\ContactDetailsSettingsView.puml
!include .\\View\Staff\Settings\ContactDetailsSettingsView.Designer.puml
!include .\\View\Staff\Settings\EmergencyContactSettingsView.puml
!include .\\View\Staff\Settings\EmergencyContactSettingsView.Designer.puml
!include .\\View\Staff\Settings\PersonalInformationSettingsView.puml
!include .\\View\Staff\Settings\PersonalInformationSettingsView.Designer.puml
!include .\\View\Staff\Settings\SecuritySettingsView.puml
!include .\\View\Staff\Settings\SecuritySettingsView.Designer.puml
!include .\\View\Staff\StaffManagement\AddStaffView.puml
!include .\\View\Staff\StaffManagement\AddStaffView.Designer.puml
!include .\\View\Staff\StaffManagement\ChangePasswordView.puml
!include .\\View\Staff\StaffManagement\ChangePasswordView.Designer.puml
!include .\\View\Staff\StaffManagement\DisplayStaffModel.puml
!include .\\View\Staff\StaffManagement\DisplayStaffView.puml
!include .\\View\Staff\StaffManagement\DisplayStaffView.Designer.puml
!include .\\View\Staff\StaffManagement\EditStaffView.puml
!include .\\View\Staff\StaffManagement\EditStaffView.Designer.puml
!include .\\View\Staff\StaffManagement\ManageStaffAppearanceSettingsView.puml
!include .\\View\Staff\StaffManagement\ManageStaffAppearanceSettingsView.Designer.puml
!include .\\View\Staff\StaffManagement\ManageStaffContactDetailsView.puml
!include .\\View\Staff\StaffManagement\ManageStaffContactDetailsView.Designer.puml
!include .\\View\Staff\StaffManagement\ManageStaffCredentialsView.puml
!include .\\View\Staff\StaffManagement\ManageStaffCredentialsView.Designer.puml
!include .\\View\Staff\StaffManagement\ManageStaffEmergencyContactDetailsView.puml
!include .\\View\Staff\StaffManagement\ManageStaffEmergencyContactDetailsView.Designer.puml
!include .\\View\Staff\StaffManagement\ManageStaffPasswordView.puml
!include .\\View\Staff\StaffManagement\ManageStaffPasswordView.Designer.puml
!include .\\View\Staff\StaffManagement\ManageStaffPersonalDetailsView.puml
!include .\\View\Staff\StaffManagement\ManageStaffPersonalDetailsView.Designer.puml
!include .\\View\Stock\StockManagement\AddStockView.puml
!include .\\View\Stock\StockManagement\AddStockView.Designer.puml
!include .\\View\Stock\StockManagement\DisplayStockModel.puml
!include .\\View\Stock\StockManagement\DisplayStockView.puml
!include .\\View\Stock\StockManagement\DisplayStockView.Designer.puml
!include .\\View\Stock\StockManagement\EditStockView.puml
!include .\\View\Stock\StockManagement\EditStockView.Designer.puml
!include .\\View\Stock\StockManagement\ManageStockDetailsView.puml
!include .\\View\Stock\StockManagement\ManageStockDetailsView.Designer.puml
!include .\\View\Stock\StockManagement\ManageStockPriceView.puml
!include .\\View\Stock\StockManagement\ManageStockPriceView.Designer.puml
!include .\\View\Stock\StockManagement\ManageStockQuantityView.puml
!include .\\View\Stock\StockManagement\ManageStockQuantityView.Designer.puml
!include .\\View\Stock\StockManagement\ManageStockWarningView.puml
!include .\\View\Stock\StockManagement\ManageStockWarningView.Designer.puml
!include .\\View\Stock\StockQuantityChanges\DisplayStockQuantityChangeModel.puml
!include .\\View\Stock\StockQuantityChanges\DisplayStockQuantityChangesView.puml
!include .\\View\Stock\StockQuantityChanges\DisplayStockQuantityChangesView.Designer.puml
!include .\\View\Stock\StockQuantityChanges\ViewStockQuantityChangeView.puml
!include .\\View\Stock\StockQuantityChanges\ViewStockQuantityChangeView.Designer.puml
@enduml
