@startuml
class EditCleaningJobPresenter {
    +  <<event>> NavigationRequest : EventHandler<NavigationEventArgs>? 
    + EditCleaningJobPresenter(view:IEditCleaningJobView, model:CleaningJobModel)
    + <<override>> CleanUp() : void
}
class "ParentEditPresenter`2"<T1,T2> {
}
"ParentEditPresenter`2" "<IEditCleaningJobView,CleaningJobModel>" <|-- EditCleaningJobPresenter
IChildPresenter <|-- EditCleaningJobPresenter
INavigatingPresenter <|-- EditCleaningJobPresenter
@enduml
