@startuml
class ManageCleaningJobOptionsPresenter {
    +  <<event>> DetailsChanged : EventHandler? 
    + ManageCleaningJobOptionsPresenter(view:IManageCleaningJobOptionsView)
}
class "DisplayPresenter`3"<T1,T2,T3> {
}
class "List`1"<T> {
}
class "Dictionary`2"<T1,T2> {
}
"DisplayPresenter`3" "<IManageCleaningJobOptionsView,CleaningJobOptionModel,DisplayCleaningJobOptionModel>" <|-- ManageCleaningJobOptionsPresenter
INotifyingChildPresenter <|-- ManageCleaningJobOptionsPresenter
ManageCleaningJobOptionsPresenter --> "Models<CleaningJobOptionModel>" "List`1"
ManageCleaningJobOptionsPresenter --> "NewQuantities<int,int>" "Dictionary`2"
@enduml
