@startuml
class ManageCleaningJobDurationPresenter {
    +  <<event>> DetailsChanged : EventHandler? 
    + ManageCleaningJobDurationPresenter(view:IManageCleaningJobDuration)
    + DatesValid : bool <<get>>
    + <<override>> CleanUp() : void
}
class "BasePresenter`1"<T> {
}
"BasePresenter`1" "<IManageCleaningJobDuration>" <|-- ManageCleaningJobDurationPresenter
INotifyingChildPresenter <|-- ManageCleaningJobDurationPresenter
ManageCleaningJobDurationPresenter --> "StartDate" DateTime
ManageCleaningJobDurationPresenter --> "EndDate" DateTime
@enduml
