@startuml
interface IAppearanceSettings {
    +  <<event>> DarkModeCheckedChanged : EventHandler? 
    +  <<event>> ToolTipsCheckedChanged : EventHandler? 
    +  <<event>> FontNameChanged : EventHandler? 
    + DarkModeChecked : bool <<get>> <<set>>
    + ShowToolTipsChecked : bool <<get>> <<set>>
    + FontName : string <<get>> <<set>>
}
ISaveCancelView <|-- IAppearanceSettings
@enduml
