@startuml
interface IContactDetailsSettings {
    +  <<event>> EmailChanged : EventHandler? 
    +  <<event>> PhoneNumberChanged : EventHandler? 
    +  <<event>> AddressChanged : EventHandler? 
    + Email : string <<get>> <<set>>
    + PhoneNumber : string <<get>> <<set>>
    + Address : string <<get>> <<set>>
    + SetEmailBorderError(isError:bool) : void
    + SetPhoneNumberBorderError(isError:bool) : void
    + ContactErrorText : string <<set>>
}
ISaveCancelView <|-- IContactDetailsSettings
@enduml
