@startuml
interface IPersonalInformationSettings {
    +  <<event>> SurnameChanged : EventHandler? 
    +  <<event>> ForenameChanged : EventHandler? 
    +  <<event>> DateOfBirthChanged : EventHandler? 
    + Forename : string <<get>> <<set>>
    + Surname : string <<get>> <<set>>
    + SetForenameBorderError(isError:bool) : void
    + SetSurnameBorderError(isError:bool) : void
    + NameErrorText : string <<set>>
    + DateOfBirthErrorText : string <<set>>
    + DateOfBirthValid : bool <<get>>
}
ISaveCancelView <|-- IPersonalInformationSettings
IPersonalInformationSettings --> "DateOfBirth" DateTime
@enduml
