@startuml
class DisplayCleaningJobOptionView <<partial>> {
    +  <<event>> Add : EventHandler? 
    +  <<event>> Edit : EventHandler? 
    +  <<event>> ArchiveToggled : EventHandler? 
    +  <<event>> ShowArchivedChanged : EventHandler? 
    +  <<event>> Search : EventHandler? 
    +  <<event>> SelectionChanged : EventHandler? 
    +  <<event>> SortRequested : EventHandler<SortRequestEventArgs>? 
    + DisplayCleaningJobOptionView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + SearchText : string <<get>> <<set>>
    + ShowArchivedItems : bool <<get>>
    + DataGridText : string <<get>> <<set>>
    + SelectedItemArchived : bool <<get>> <<set>>
    + DisplayItems(items:BindingList<DisplayCleaningJobOptionModel>) : void
    + DisableAll() : void
    + EnableAll() : void
    + CleanUp() : void
}
class "IDisplayView`1"<T> {
}
Form <|-- DisplayCleaningJobOptionView
"IDisplayView`1" "<DisplayCleaningJobOptionModel>" <|-- DisplayCleaningJobOptionView
IChildView <|-- DisplayCleaningJobOptionView
IThemeable <|-- DisplayCleaningJobOptionView
IDisplayCleaningJobOptionView <|-- DisplayCleaningJobOptionView
DisplayCleaningJobOptionView --> "SelectedItem" DisplayCleaningJobOptionModel
@enduml
