@startuml
class CleaningJobOptionModel {
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + UnitCost : decimal <<get>> <<set>>
    + Archived : bool <<get>> <<set>>
    + Quantity : int <<get>> <<set>>
    + CostAtTime : decimal <<get>> <<set>>
}
@enduml
