@startuml
class PersonalInformationSettingsView <<partial>> {
    +  <<event>> ForenameChanged : EventHandler? 
    +  <<event>> SurnameChanged : EventHandler? 
    +  <<event>> DateOfBirthChanged : EventHandler? 
    +  <<event>> Save : EventHandler? 
    +  <<event>> Cancel : EventHandler? 
    + PersonalInformationSettingsView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + SaveCancelVisible : bool <<set>>
    + Forename : string <<get>> <<set>>
    + Surname : string <<get>> <<set>>
    + NameErrorText : string <<set>>
    + DateOfBirthErrorText : string <<set>>
    + SetForenameBorderError(isError:bool) : void
    + SetSurnameBorderError(isError:bool) : void
    + IsLoading : bool <<get>> <<set>>
    + DateOfBirthValid : bool <<get>>
    + ShowMessageBox(text:string, caption:string, buttons:MessageBoxButtons) : DialogResult
    + CleanUp() : void
}
Form <|-- PersonalInformationSettingsView
IPersonalInformationSettings <|-- PersonalInformationSettingsView
IThemeable <|-- PersonalInformationSettingsView
PersonalInformationSettingsView --> "DateOfBirth" DateTime
@enduml
