@startuml
class SecuritySettingsView <<partial>> {
    +  <<event>> Save : EventHandler? 
    +  <<event>> Cancel : EventHandler? 
    +  <<event>> NewPasswordChanged : EventHandler? 
    + SecuritySettingsView()
    + Theme() : void
    + SetToolTipVisibility() : void
    + SetFont() : void
    + SaveCancelVisible : bool <<set>>
    + IsLoading : bool <<get>> <<set>>
    + Username : string <<set>>
    + PrivilegeLevel : string <<set>>
    + CurrentPassword : string <<get>>
    + NewPassword : string <<get>>
    + ConfirmPassword : string <<get>>
    + EightLong : bool <<get>> <<set>>
    + Number : bool <<get>> <<set>>
    + SpecialCharacter : bool <<get>> <<set>>
    + UppercaseLowercase : bool <<get>> <<set>>
    + PasswordError : string <<set>>
    + Reset() : void
    + SetCurrentPasswordBorderError(isError:bool) : void
    + SetNewPasswordBorderError(isError:bool) : void
    + SetConfirmPasswordBorderError(isError:bool) : void
    + ShowMessageBox(text:string, caption:string, buttons:MessageBoxButtons) : DialogResult
    + CleanUp() : void
}
Form <|-- SecuritySettingsView
ISecuritySettingsView <|-- SecuritySettingsView
IThemeable <|-- SecuritySettingsView
@enduml
